repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.2
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3
    hooks:
      - id: ruff-check
        args: [--select, I, --fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        exclude: ^docs/openapi\.json$
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
  - repo: local
    hooks:
      - id: render-openapi
        name: render-openapi
        entry: scripts/render-openapi
        language: script
