[DEFAULT]
# Same as -b on the CLI. We always want this, otherwise you get propmted
# to apply each migration.
batch_mode = on
sources = src/openvols/data/postgres/migrations
# database
# Set the Postgres DSN in an environment specific file that includes this one
# See yoyo-dev.ini for an example.
