#!/usr/bin/env bash

echo "Waiting for postgres health check to succeed..."

until [ "$(docker inspect --format='{{.State.Health.Status}}' postgres 2>/dev/null)" == "healthy" ]; do
    printf "."
    sleep 1
done

echo -e "\npostgres health check succeeded."
